name: foxShop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  audio_waveforms: ^1.2.0
  cached_network_image: ^3.4.1 
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.2
  crypto: ^3.0.6
  device_info_plus: ^11.3.0
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_blurhash: ^0.8.2
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2
  http: ^1.3.0
  hydrated_bloc: ^10.0.0
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  location: ^8.0.0
  logger: ^2.5.0
  lottie: ^3.3.1
  onesignal_flutter:
    git:
      url: https://github.com/milansurelia/OneSignal-Flutter-SDK.git
  otp_autofill: ^4.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_manager: ^3.6.3
  photo_manager_image_provider: ^2.2.0
  photo_view: ^0.15.0
  pinput: ^5.0.1
  pusher_channels_flutter: ^2.4.0
  shared_preferences: ^2.3.5
  smooth_page_indicator: ^1.2.0+3
  sms_autofill: ^2.4.1
  sqflite: ^2.4.1
  typesense: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/
    - assets/logo/logo-development.png
    - assets/country_code.json
    - .env

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans.ttf
