name: logic_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.2
  crypto: ^3.0.6
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_blurhash: ^0.8.2
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.6.3
  http: ^1.3.0
  hydrated_bloc: ^10.0.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  logger: ^2.5.0
  onesignal_flutter: ^5.2.9
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_manager: ^3.6.3
  pusher_channels_flutter: ^2.5.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
